import React from 'react';
import {
  ScrollView,
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';

const LAST_UPDATED = 'April 4, 2026';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body:
      'By downloading or using Everyone 72, you agree to these Terms of Service. ' +
      'If you do not agree, please do not use the app. ' +
      'You must be at least 13 years old to use Everyone 72.',
  },
  {
    title: '2. Description of Service',
    body:
      'Everyone 72 is a golf round-tracking app that provides:\n' +
      '• Score and statistics tracking\n' +
      '• AI-powered coaching analysis (via Anthropic Claude)\n' +
      '• Practice session sharing with friends\n' +
      '• Leaderboards and social features\n\n' +
      'The AI analysis is for informational and entertainment purposes only and does not constitute professional golf coaching.',
  },
  {
    title: '3. User Accounts',
    body:
      'You are responsible for maintaining the confidentiality of your account credentials. ' +
      'You are responsible for all activity that occurs under your account. ' +
      'Notify us immediately at support@everyone72.com if you suspect unauthorized use.',
  },
  {
    title: '4. User Content',
    body:
      'You retain ownership of content you post (photos, notes). ' +
      'By posting content, you grant Everyone 72 a limited, non-exclusive license to display that content ' +
      'to your connected friends within the app. ' +
      'You may not post content that is illegal, harmful, or violates others\' rights.',
  },
  {
    title: '5. Prohibited Uses',
    body:
      'You may not:\n' +
      '• Use the app for any illegal purpose\n' +
      '• Attempt to reverse-engineer or hack the app\n' +
      '• Create fake accounts or impersonate others\n' +
      '• Spam or harass other users\n' +
      '• Use automated tools to scrape data from the app',
  },
  {
    title: '6. AI Analysis Disclaimer',
    body:
      'The AI coaching analysis is generated by Anthropic\'s Claude model and is provided "as is." ' +
      'It is intended as a fun, educational tool — not professional golf instruction. ' +
      'We are not responsible for any decisions made based on AI analysis. ' +
      'Always consult a qualified golf professional for serious instruction.',
  },
  {
    title: '7. Limitation of Liability',
    body:
      'To the maximum extent permitted by law, Everyone 72 shall not be liable for any indirect, ' +
      'incidental, special, or consequential damages arising from your use of the app, ' +
      'including loss of data or profits.',
  },
  {
    title: '8. Termination',
    body:
      'We reserve the right to suspend or terminate your account for violation of these terms. ' +
      'You may delete your account at any time by contacting support@everyone72.com.',
  },
  {
    title: '9. Changes to Terms',
    body:
      'We may update these terms from time to time. ' +
      'We will notify you of material changes via the app. ' +
      'Continued use after changes constitutes acceptance.',
  },
  {
    title: '10. Contact',
    body:
      'Questions about these Terms? Contact us:\n\n' +
      'Email: support@everyone72.com\n' +
      'Website: https://everyone72.com',
  },
];

export default function TermsScreen() {
  const navigation = useNavigation();

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={24} color="#1a472a" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.intro}>
          These Terms of Service govern your use of the Everyone 72 mobile application.
          Please read them carefully.
        </Text>
        <Text style={styles.lastUpdated}>Last updated: {LAST_UPDATED}</Text>

        {SECTIONS.map((s) => (
          <View key={s.title} style={styles.section}>
            <Text style={styles.sectionTitle}>{s.title}</Text>
            <Text style={styles.sectionBody}>{s.body}</Text>
          </View>
        ))}

        <View style={styles.footer}>
          <Text style={styles.footerText}>© 2026 Everyone 72. All rights reserved.</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 17, fontWeight: '600', color: '#111' },
  content: { padding: 20, paddingBottom: 40 },
  intro: { fontSize: 15, color: '#374151', lineHeight: 22, marginBottom: 4 },
  lastUpdated: { fontSize: 13, color: '#9ca3af', marginBottom: 24 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: '#1a472a', marginBottom: 8 },
  sectionBody: { fontSize: 14, color: '#4b5563', lineHeight: 22 },
  footer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    alignItems: 'center',
  },
  footerText: { fontSize: 12, color: '#9ca3af' },
});
